credentials:
  usernames:
    diretor:
      name: Diretor
      password: '$2b$12$43PuvK9bJxBIIj8z826AGeVLSIo.SMqq9gvUaxoH9.FT28cLmX13a'  # senha: diretor123
      email: tbac@discente.ifpe.edu.br
      role: Diretor

cookie:
  name: auth_cookie
  key: assinatura_secreta
  expiry_days: 0